// CAZADOR 1.0 · Experiencia Premium
(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=u=>{try{const x=new URL(String(u||''));return x.protocol==='https:'?x.toString():''}catch{return''}};
let categories=[],allCategories=false,lastQuery='',currentMasters=[],currentDiscovered=[],homeMasters=[],homeDiscovered=[],suggestTimer=null,providerStatus={emailConfigured:false,whatsappEnabled:false};
const session=(()=>{try{let s=sessionStorage.getItem('cazador_session_v1');if(!s){s=crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now();sessionStorage.setItem('cazador_session_v1',s)}return s}catch{return Math.random().toString(36).slice(2)}})();

async function api(path,options={}){const r=await fetch(BASE+path,{...options,headers:{Authorization:`Bearer ${ANON}`,apikey:ANON,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||d?.message||`Error ${r.status}`);return d}
async function publicApi(path){const r=await fetch(BASE+path,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`Error ${r.status}`);return d}
async function track(event_type,data={}){try{await api('/cazador-event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_type,session,...data})})}catch{}}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__cazToast);window.__cazToast=setTimeout(()=>t.classList.remove('show'),3900)}
function fmtDate(v){if(!v)return'';try{return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short'}).format(new Date(v))}catch{return''}}
function recIcon(r){return r==='COMPRAR AHORA'?'🔥':r==='MUY BUENA OPORTUNIDAD'?'🟢':r==='BUENA OPORTUNIDAD'?'🟢':r==='MEJOR ESPERAR'?'🔴':r==='PRECIO NORMAL'?'🟡':'👀'}
function recClass(r){if(['COMPRAR AHORA','MUY BUENA OPORTUNIDAD','BUENA OPORTUNIDAD'].includes(r))return'good';if(r==='MEJOR ESPERAR')return'wait';if(r==='PRECIO NORMAL')return'normal';return'watch'}
function setLoading(on){$('#loading')?.classList.toggle('show',on);const b=$('#searchBtn');if(b){b.disabled=on;b.textContent=on?'Comparando…':'Buscar y comparar'}}
function showResults(){const p=$('#resultados');p?.classList.add('show')}
function hideSuggest(){$('#suggest')?.classList.remove('show')}
function normalizePhone(v){const d=String(v||'').replace(/[^0-9]/g,'');if(!d)return'';if(d.startsWith('56'))return'+'+d;if(d.startsWith('9')&&d.length===9)return'+56'+d;return'+'+d}
function discountText(x){const type=String(x?.discount_type||'').toLowerCase(),v=Number(x?.discount_value||0);if(!v)return x?.title||'Beneficio';if(type.includes('percent')||type.includes('porcent'))return `${v}%`;if(type.includes('fixed')||type.includes('monto')||type.includes('amount'))return money(v);return `${v}${type?' '+type:''}`}

function renderCategories(){const grid=$('#categoryGrid');if(!grid)return;const visible=allCategories?categories:categories.filter(c=>c.featured).slice(0,8);grid.innerHTML=visible.map(c=>`<button class="categoryBtn" data-cat="${esc(c.slug)}" data-name="${esc(c.name)}"><span class="ico">${esc(c.icon||'📂')}</span>${esc(c.name)}<small>${Number(c.total_count||0)>0?`${Number(c.total_count)} detectados`:'preparada'}</small></button>`).join('');const t=$('#toggleCategories');if(t)t.textContent=allCategories?'Ver principales':'Ver todas'}

function masterMini(p,i){const best=(p.offers||[]).find(o=>Number(o.current_price)>0)||(p.offers||[])[0]||{};return `<article class="miniDeal"><div class="miniPic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.canonical_name)}" loading="lazy">`:'🎯'}</div><div class="miniBody"><h3>${esc(p.canonical_name)}</h3>${p.best_price?`<div class="miniPrice">${money(p.best_price)}</div>`:'<div class="miniPrice">Sin precio</div>'}<div class="miniMeta">${esc(recIcon(p.recommendation))} ${esc(p.recommendation||'SEGUIR VIGILANDO')}${p.best_price?` · Score ${Number(p.cazador_score||0)}/100`:''}</div><div class="miniAction"><button class="softBtn" data-watch-home-master="${i}">🔔 Vigilar</button>${best.outbound_url?`<a class="darkBtn" href="${esc(best.outbound_url)}" target="_blank" rel="noopener noreferrer" data-deal-product="${esc(p.product_id)}">Ver oferta</a>`:'<button class="softBtn" disabled>Sin precio</button>'}</div></div></article>`}
function discoveredMini(d,i){return `<article class="miniDeal"><div class="miniPic">${d.image_url?`<img src="${esc(d.image_url)}" alt="${esc(d.title)}" loading="lazy">`:'🔎'}</div><div class="miniBody"><h3>${esc(d.title)}</h3>${d.current_price?`<div class="miniPrice">${money(d.current_price)}</div>`:'<div class="miniPrice">En validación</div>'}<div class="miniMeta">${esc(d.store||d.source||'Fuente')} · identidad aún no fusionada</div><div class="miniAction"><button class="softBtn" data-watch-home-listing="${i}">🔔 Vigilar</button>${d.outbound_url?`<a class="darkBtn" href="${esc(d.outbound_url)}" target="_blank" rel="noopener noreferrer">Ver</a>`:''}</div></div></article>`}
function renderHomeDeals(deals){const grid=$('#homeDeals');if(!grid)return;homeMasters=deals?.products||[];homeDiscovered=deals?.discovered||[];const priced=homeMasters.filter(p=>Number(p.best_price)>0);const fallback=homeDiscovered.filter(d=>Number(d.current_price)>0);let html='';if(priced.length)html=priced.slice(0,4).map(masterMini).join('');else if(fallback.length)html=fallback.slice(0,4).map(discoveredMini).join('');else html='<div class="empty"><strong>Aún no hay una oportunidad con precio confirmado</strong>El robot seguirá incorporando productos y el monitor continuará revisando precios.</div>';grid.innerHTML=html;const radar=$('#radarDeal'),p=priced[0],d=fallback[0];if(radar){if(p)radar.innerHTML=`<small>MEJOR OPORTUNIDAD DETECTADA</small><h3>${esc(p.canonical_name)}</h3><div class="big">${money(p.best_price)}</div><div style="font-size:10px;color:#667085">${esc(recIcon(p.recommendation))} ${esc(p.recommendation)} · Score ${Number(p.cazador_score||0)}/100</div>`;else if(d)radar.innerHTML=`<small>PRECIO DETECTADO EN VALIDACIÓN</small><h3>${esc(d.title)}</h3><div class="big">${money(d.current_price)}</div><div style="font-size:10px;color:#667085">Cazador valida la variante exacta antes de puntuar</div>`;else radar.innerHTML='<small>RADAR ACTIVO</small><h3>Seguimos reuniendo precios</h3><div class="big">Vigilando</div>'}}

function couponCard(c){const source=safeUrl(c.source_url),verified=fmtDate(c.verified_at);return `<article class="benefitCard"><div class="label">${esc(c.store||'Cupón')}</div><h3>${esc(c.title||'Descuento disponible')}</h3><div class="benefitBig">${esc(discountText(c))}</div>${c.code?`<button class="code" data-copy-code="${esc(c.code)}">${esc(c.code)} · copiar</button>`:''}<p>${c.minimum_purchase?`Compra mínima ${money(c.minimum_purchase)}. `:''}${c.maximum_discount?`Tope ${money(c.maximum_discount)}. `:''}${verified?`Verificado ${verified}.`:''}</p>${c.terms?`<p>${esc(String(c.terms).slice(0,180))}</p>`:''}${source?`<p><a href="${esc(source)}" target="_blank" rel="noopener noreferrer" data-coupon-view="${esc(c.id)}" style="font-weight:900;color:#175cd3">Ver fuente y condiciones →</a></p>`:''}</article>`}
function benefitCard(b){const source=safeUrl(b.source_url),verified=fmtDate(b.verified_at),days=Array.isArray(b.valid_weekdays)&&b.valid_weekdays.length?` · ${b.valid_weekdays.join(', ')}`:'';return `<article class="benefitCard"><div class="label">${esc(b.provider_name||'Beneficio')} ${b.store?`· ${esc(b.store)}`:''}</div><h3>${esc(b.title||b.payment_product||'Beneficio de pago')}</h3><div class="benefitBig">${esc(discountText(b))}</div><p>${esc(b.payment_product||'')}${esc(days)}${b.minimum_purchase?` · mínimo ${money(b.minimum_purchase)}`:''}${b.maximum_discount?` · tope ${money(b.maximum_discount)}`:''}</p>${b.terms?`<p>${esc(String(b.terms).slice(0,180))}</p>`:''}${verified?`<p>Verificado ${verified}.</p>`:''}${source?`<p><a href="${esc(source)}" target="_blank" rel="noopener noreferrer" data-benefit-view="${esc(b.id)}" style="font-weight:900;color:#175cd3">Ver condiciones →</a></p>`:''}</article>`}
function renderCoupons(arr){const g=$('#couponGrid');if(!g)return;g.innerHTML=arr?.length?arr.slice(0,6).map(couponCard).join(''):'<div class="empty"><strong>No hay cupones verificados cargados hoy</strong>Cazador mostrará aquí sólo códigos vigentes y comprobados.</div>'}
function renderBenefits(arr){const g=$('#benefitGrid');if(!g)return;g.innerHTML=arr?.length?arr.slice(0,6).map(benefitCard).join(''):'<div class="empty"><strong>No hay beneficios bancarios verificados cargados hoy</strong>Cuando integremos uno, sus condiciones y elegibilidad aparecerán aquí.</div>'}

function masterCard(p,i){const offers=p.offers||[],priced=offers.filter(o=>Number(o.current_price)>0),best=priced[0]||offers[0]||{},stores=offers.slice(0,4).map(o=>`${esc(o.store||o.source)} ${o.current_price?money(o.current_price):'—'}`).join(' · '),hist=[];if(p.average_30d)hist.push(`Prom. 30d ${money(p.average_30d)}`);if(p.minimum_90d)hist.push(`Mín. 90d ${money(p.minimum_90d)}`);if(p.maximum_90d)hist.push(`Máx. 90d ${money(p.maximum_90d)}`);return `<article class="productCard"><div class="productPic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.canonical_name)}" loading="lazy">`:'🎯'}</div><div class="productInfo"><div class="subline">${p.category?`${esc(p.category.icon||'📂')} ${esc(p.category.name)} · `:''}${esc(p.brand||'Producto')}${p.model?` · ${esc(p.model)}`:''}</div><h3>${esc(p.canonical_name)}</h3><span class="rec ${recClass(p.recommendation)}">${esc(recIcon(p.recommendation))} ${esc(p.recommendation||'SEGUIR VIGILANDO')}</span><div class="explain">${esc(p.explanation||'Cazador sigue reuniendo información.')}</div>${hist.length?`<div class="history">${hist.map(x=>`<span>${x}</span>`).join('')}</div>`:''}</div><div class="productBuy"><div class="bestLabel">${p.best_price?'Mejor precio disponible':'Precio'}</div><div class="bestPrice">${p.best_price?money(p.best_price):'Sin confirmar'}</div>${p.best_price?`<div class="scoreLine">Cazador Score ${Number(p.cazador_score||0)}/100 · ${Number(p.priced_stores||0)} tienda(s)</div>`:'<div class="scoreLine" style="color:#667085">Sin puntuar hasta confirmar precio</div>'}${stores?`<div class="storeLines">${stores}</div>`:''}<div class="actionRow"><button class="watchBtn" data-watch-master="${i}">🔔 Vigilar</button>${best.outbound_url?`<a class="buyBtn" href="${esc(best.outbound_url)}" target="_blank" rel="noopener noreferrer" data-deal-product="${esc(p.product_id)}">Comprar mejor opción</a>`:'<button class="watchBtn" disabled>Sin compra</button>'}</div></div></article>`}
function validationCard(d,i){const cat=d.category?`${esc(d.category.icon||'📂')} ${esc(d.category.name)} · `:'';return `<article class="productCard validation"><div class="productPic">${d.image_url?`<img src="${esc(d.image_url)}" alt="${esc(d.title)}" loading="lazy">`:'🔎'}</div><div class="productInfo"><span class="validationBadge">EN VALIDACIÓN</span><div class="subline">${cat}${esc(d.store||d.source||'Fuente')}</div><h3>${esc(d.title)}</h3><div class="explain">${esc(d.notice||'Cazador todavía valida la variante exacta. No la mezclamos con otros productos hasta tener suficiente confianza.')}</div></div><div class="productBuy"><div class="bestLabel">Precio detectado</div><div class="bestPrice">${d.current_price?money(d.current_price):'Sin confirmar'}</div><div class="scoreLine" style="color:#667085">Sin Cazador Score mientras esté en validación</div><div class="actionRow"><button class="watchBtn" data-watch-listing="${i}">🔔 Vigilar publicación</button>${d.outbound_url?`<a class="buyBtn" href="${esc(d.outbound_url)}" target="_blank" rel="noopener noreferrer">Ver tienda</a>`:''}</div></div></article>`}
function renderSearch(products,discovered,context='search'){currentMasters=products||[];currentDiscovered=discovered||[];const list=$('#productList');if(!list)return;let html='';if(currentMasters.length)html+=currentMasters.map(masterCard).join('');if(currentDiscovered.length)html+=currentDiscovered.map(validationCard).join('');if(!html)html=`<div class="empty"><strong>${context==='category'?'Todavía no hay productos cargados en esta categoría':'No encontramos una coincidencia suficientemente clara'}</strong>${context==='category'?'El robot seguirá poblando el catálogo automáticamente.':'Prueba con marca + modelo o una búsqueda más general.'}</div>`;list.innerHTML=html}

function applyWatch(p,linkId=null){if(!p)return;$('#watchProductId').value=p.product_id||'';$('#watchItem').value=linkId||'';$('#watchProduct').value=p.canonical_name||p.title||lastQuery;const price=p.best_price||p.current_price;$('#watchPrice').value=price?Math.round(Number(price)*.95):'';focusWatch(true)}
function setMasterWatch(i){applyWatch(currentMasters[i])}
function setListingWatch(i){const d=currentDiscovered[i];applyWatch(d,d?.link_id||null)}
function setHomeMasterWatch(i){applyWatch(homeMasters[i])}
function setHomeListingWatch(i){const d=homeDiscovered[i];applyWatch(d,d?.link_id||null)}
function focusWatch(keep=false){if(!keep&&!$('#watchProduct').value)$('#watchProduct').value=lastQuery;$('#alertas')?.scrollIntoView({behavior:'smooth'});setTimeout(()=>$('#watchPrice')?.focus(),300)}
window.focusWatch=focusWatch;

async function saveWatch(){const product=$('#watchProduct').value.trim(),raw=$('#watchPrice').value.replace(/[^0-9]/g,''),target=raw?Number(raw):null,linkId=$('#watchItem').value.trim()||null,productId=$('#watchProductId').value.trim()||null,email=$('#watchEmail').value.trim(),phone=normalizePhone($('#watchPhone').value),wantEmail=$('#chEmail').checked,wantWa=$('#chWhatsapp').checked;if(product.length<2){toast('Escribe el producto que quieres vigilar.');return}if(!wantEmail&&!wantWa){toast('Selecciona correo o WhatsApp.');return}if(wantEmail&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)){toast('Escribe un correo válido.');return}if(wantWa&&!providerStatus.whatsappEnabled){toast('WhatsApp todavía no está conectado. Usa correo por ahora.');return}if(wantWa&&phone.length<11){toast('Escribe un WhatsApp válido con código de país.');return}const channels=[];if(wantEmail)channels.push('email');if(wantWa)channels.push('whatsapp');const btn=$('#watchBtn');btn.disabled=true;btn.textContent='Guardando…';try{const r=await api('/cazador-watch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:product,product_link_id:linkId,product_id:productId,product_name:product,target_price:target,trigger_mode:target?'target_price':'great_deal',min_deal_score:80,alert_on_best_price:true,source:'premium-web',email:wantEmail?email:null,phone:wantWa?phone:null,notify_channel:wantEmail&&wantWa?'email_whatsapp':wantWa?'whatsapp':'email',notify_channels:channels})});if(wantEmail&&!providerStatus.emailConfigured)toast('🎯 Vigilancia guardada. El correo quedará listo al conectar el proveedor de envío.');else toast(r.scope==='master_product'?'🎯 Producto completo en vigilancia.':'🎯 Seguimiento guardado.');$('#watchItem').value='';$('#watchProductId').value=''}catch(e){toast('No pudimos guardar el seguimiento: '+e.message)}finally{btn.disabled=false;btn.textContent='Poner en el Cazador'}}

async function loadSuggest(q){try{const d=await api('/cazador-intelligence?mode=suggest&q='+encodeURIComponent(q));if($('#q').value.trim()!==q)return;const products=d.products||[],disc=d.discovered||[],cats=d.categories||[],box=$('#suggest');if(!products.length&&!disc.length&&!cats.length){hideSuggest();return}let h='';if(products.length)h+='<div class="suggestTitle">Productos Maestros</div>'+products.slice(0,6).map(p=>`<button type="button" class="suggestItem" data-suggest-product="${esc(p.name)}">${p.image_url?`<img class="suggestThumb" src="${esc(p.image_url)}" alt="">`:'<span class="suggestIcon">🎯</span>'}<span><b>${esc(p.name)}</b><small>${esc([p.brand,p.model].filter(Boolean).join(' · ')||'Producto confirmado')}</small></span></button>`).join('');if(disc.length)h+='<div class="suggestTitle">También encontramos</div>'+disc.slice(0,4).map(x=>`<button type="button" class="suggestItem" data-suggest-product="${esc(x.title)}"><span class="suggestIcon">🔎</span><span><b>${esc(x.title)}</b><small>En validación · ${esc(x.store||x.source||'fuente')}</small></span></button>`).join('');if(cats.length)h+='<div class="suggestTitle">Categorías</div>'+cats.slice(0,4).map(c=>`<button type="button" class="suggestItem" data-suggest-cat="${esc(c.slug)}" data-name="${esc(c.name)}"><span class="suggestIcon">${esc(c.icon||'📂')}</span><span><b>${esc(c.name)}</b><small>Explorar categoría</small></span></button>`).join('');box.innerHTML=h;box.classList.add('show')}catch{hideSuggest()}}

async function searchDeals(qOverride=null){const q=String(qOverride||$('#q').value).trim();if(q.length<2){toast('Escribe el producto que quieres buscar.');return}$('#q').value=q;lastQuery=q;hideSuggest();showResults();setLoading(true);$('#productList').innerHTML='';$('#resultTitle').textContent=`Buscando “${q}”`;$('#resultSubtitle').textContent='Cazador separa variantes y no fuerza coincidencias dudosas.';$('#resultInfo').classList.remove('show');track('search',{query:q});try{await Promise.all([api('/meli-search?q='+encodeURIComponent(q)).catch(()=>null),publicApi('/retail-search?q='+encodeURIComponent(q)).catch(()=>null)]);const intel=await api('/cazador-intelligence?q='+encodeURIComponent(q));const products=intel.products||[],disc=intel.discovered||[];renderSearch(products,disc);const info=$('#resultInfo');info.textContent=products.length?`Cazador identificó ${products.length} Producto(s) Maestro. ${disc.length?`${disc.length} publicación(es) permanecen separadas mientras se valida su variante.`:''}`:`Encontramos ${disc.length} publicación(es), pero todavía no existe suficiente evidencia para fusionarlas como el mismo producto.`;info.classList.add('show');$('#resultTag').textContent=products.length?'PRODUCTOS COMPARADOS':'CATÁLOGO EN VALIDACIÓN'}catch(e){$('#productList').innerHTML=`<div class="empty"><strong>No pudimos completar la búsqueda</strong>${esc(e.message)}</div>`}finally{setLoading(false);$('#resultados').scrollIntoView({behavior:'smooth',block:'start'})}}

async function browseCategory(slug,name){lastQuery=name||slug;showResults();setLoading(true);$('#resultTitle').textContent=name||'Categoría';$('#resultSubtitle').textContent='Productos confirmados y publicaciones en validación, siempre separados.';$('#resultInfo').classList.remove('show');track('category_view',{category_slug:slug});try{const d=await api('/cazador-intelligence?category='+encodeURIComponent(slug));renderSearch(d.products||[],d.discovered||[],'category');$('#resultTag').textContent=slug==='ofertas'?'RADAR DE OFERTAS':'CATEGORÍA';const info=$('#resultInfo');info.textContent=`${name||slug}: ${Number((d.products||[]).length)} Producto(s) Maestro y ${Number((d.discovered||[]).length)} publicación(es) aún en validación.`;info.classList.add('show')}catch(e){$('#productList').innerHTML=`<div class="empty"><strong>No pudimos abrir esta categoría</strong>${esc(e.message)}</div>`}finally{setLoading(false);$('#resultados').scrollIntoView({behavior:'smooth'})}}

async function loadStatus(){try{const s=await api('/cazador-status');providerStatus.emailConfigured=Boolean(s.providers?.email?.configured);providerStatus.whatsappEnabled=Boolean(s.providers?.whatsapp?.enabled);const wa=$('#chWhatsapp');if(wa){wa.disabled=!providerStatus.whatsappEnabled;if(!providerStatus.whatsappEnabled)wa.checked=false}const note=$('.watchNote');if(note){const parts=[];parts.push(providerStatus.emailConfigured?'Correo conectado.':'Correo preparado, pendiente de conectar proveedor.');parts.push(providerStatus.whatsappEnabled?'WhatsApp conectado.':'WhatsApp todavía no conectado.');note.textContent=parts.join(' ')}}catch{}}
async function loadHome(){try{const d=await api('/cazador-intelligence?mode=home');categories=d.categories||[];renderCategories();$('#statCatalog').textContent=Number(d.stats?.catalog_items||0).toLocaleString('es-CL');$('#statMaster').textContent=Number(d.stats?.master_products||0).toLocaleString('es-CL');$('#statCategories').textContent=Number(d.stats?.categories_with_catalog||0).toLocaleString('es-CL');renderHomeDeals(d.deals||{});renderCoupons(d.coupons||[]);renderBenefits(d.benefits||[])}catch(e){console.warn('home',e);$('#homeDeals').innerHTML='<div class="empty"><strong>No pudimos cargar el Radar</strong>La búsqueda sigue disponible.</div>';renderCoupons([]);renderBenefits([])}}

$('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();searchDeals()});
$('#q')?.addEventListener('input',e=>{clearTimeout(suggestTimer);const q=e.target.value.trim();if(q.length<2){hideSuggest();return}suggestTimer=setTimeout(()=>loadSuggest(q),180)});
$('#q')?.addEventListener('keydown',e=>{if(e.key==='Escape')hideSuggest()});
document.addEventListener('click',e=>{const t=e.target.closest?.('[data-suggest-product],[data-suggest-cat],[data-cat],[data-quick],[data-watch-master],[data-watch-listing],[data-watch-home-master],[data-watch-home-listing],[data-copy-code],[data-coupon-view],[data-benefit-view],[data-deal-product]');if(!t){if(!e.target.closest?.('#searchForm'))hideSuggest();return}if(t.dataset.suggestProduct){hideSuggest();searchDeals(t.dataset.suggestProduct)}else if(t.dataset.suggestCat){hideSuggest();browseCategory(t.dataset.suggestCat,t.dataset.name)}else if(t.dataset.cat){browseCategory(t.dataset.cat,t.dataset.name)}else if(t.dataset.quick){searchDeals(t.dataset.quick)}else if(t.dataset.watchMaster!==undefined){setMasterWatch(Number(t.dataset.watchMaster))}else if(t.dataset.watchListing!==undefined){setListingWatch(Number(t.dataset.watchListing))}else if(t.dataset.watchHomeMaster!==undefined){setHomeMasterWatch(Number(t.dataset.watchHomeMaster))}else if(t.dataset.watchHomeListing!==undefined){setHomeListingWatch(Number(t.dataset.watchHomeListing))}else if(t.dataset.copyCode){navigator.clipboard?.writeText(t.dataset.copyCode).then(()=>toast('Cupón copiado: '+t.dataset.copyCode)).catch(()=>toast('Código: '+t.dataset.copyCode));track('coupon_view')}else if(t.dataset.couponView){track('coupon_view',{metadata:{coupon_id:t.dataset.couponView}})}else if(t.dataset.benefitView){track('benefit_view',{metadata:{benefit_id:t.dataset.benefitView}})}else if(t.dataset.dealProduct){track('deal_view',{product_id:t.dataset.dealProduct})}});
$('#toggleCategories')?.addEventListener('click',()=>{allCategories=!allCategories;renderCategories()});
$('#refreshDeals')?.addEventListener('click',loadHome);
$('#watchBtn')?.addEventListener('click',saveWatch);
$('#mobileSearch')?.addEventListener('click',()=>{$('#inicio')?.scrollIntoView({behavior:'smooth'});setTimeout(()=>$('#q')?.focus(),300)});
$('#mobileWatch')?.addEventListener('click',()=>focusWatch());
track('page_view');Promise.all([loadHome(),loadStatus()]);
})();
